<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Quote {{ $quote->quote_number }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 13px; color: #333; }
        .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
        h1 { color: #E8694A; font-size: 28px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f0f2f5; padding: 8px 12px; text-align: left; font-size: 12px; text-transform: uppercase; }
        td { padding: 8px 12px; border-bottom: 1px solid #eee; }
        .text-right { text-align: right; }
        .totals td { font-weight: bold; }
        .status-badge { display: inline-block; padding: 3px 10px; border-radius: 4px; font-size: 11px; background: #FDF0EC; color: #E8694A; }
        .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 15px; }
    </style>
</head>
<body>
<div class="header">
    <div>
        <h1>QUOTE</h1>
        <p><strong>{{ $quote->quote_number }}</strong></p>
        <p>Date: {{ $quote->created_at->format('d F Y') }}</p>
        @if($quote->valid_until)
        <p>Valid Until: {{ $quote->valid_until->format('d F Y') }}</p>
        @endif
    </div>
    <div style="text-align:right">
        <h3 style="color:#E8694A">IntuDash</h3>
        <p>SMS Campaign Services</p>
        <p><span class="status-badge">{{ ucfirst($quote->status) }}</span></p>
    </div>
</div>

<div style="display:flex; justify-content:space-between; margin-bottom:20px;">
    <div>
        <strong>Quote For:</strong><br>
        {{ $quote->client->company_name }}<br>
        {{ $quote->client->contact_person }}<br>
        {{ $quote->client->email }}<br>
        @if($quote->client->billing_address){{ $quote->client->billing_address }}<br>@endif
        @if($quote->client->vat_number)VAT: {{ $quote->client->vat_number }}@endif
    </div>
    <div>
        <strong>Campaign:</strong><br>
        {{ $quote->campaign?->name ?? '—' }}
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Description</th>
            <th class="text-right">Quantity</th>
            <th class="text-right">Unit Price</th>
            <th class="text-right">Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach($quote->items as $item)
        <tr>
            <td>{{ $item->description }}</td>
            <td class="text-right">{{ number_format($item->quantity) }}</td>
            <td class="text-right">R {{ number_format($item->unit_price, 4) }}</td>
            <td class="text-right">R {{ number_format($item->total, 2) }}</td>
        </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr><td colspan="3" class="text-right">Subtotal</td><td class="text-right">R {{ number_format($quote->subtotal, 2) }}</td></tr>
        @if($quote->vat_enabled)
        <tr><td colspan="3" class="text-right">VAT ({{ $quote->vat_rate }}%)</td><td class="text-right">R {{ number_format($quote->vat_amount, 2) }}</td></tr>
        @endif
        <tr class="totals"><td colspan="3" class="text-right" style="font-size:15px">TOTAL</td><td class="text-right" style="font-size:15px">R {{ number_format($quote->total, 2) }}</td></tr>
    </tfoot>
</table>

@if($quote->notes)
<div style="margin-top:20px;">
    <strong>Notes:</strong>
    <p>{{ $quote->notes }}</p>
</div>
@endif

<div class="footer">
    <p>This quote is valid for 30 days from the issue date. To accept this quote, please contact us.</p>
    <p>Generated by IntuDash SMS Campaign Manager</p>
</div>
</body>
</html>
