<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 13px; color: #333; }
        .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
        h1 { color: #6c63ff; font-size: 28px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f0f2f5; padding: 8px 12px; text-align: left; font-size: 12px; text-transform: uppercase; }
        td { padding: 8px 12px; border-bottom: 1px solid #eee; }
        .text-right { text-align: right; }
        .totals td { font-weight: bold; }
        .badge { display: inline-block; padding: 3px 10px; border-radius: 4px; font-size: 11px; background: #e8f5e9; color: #2e7d32; }
        .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 15px; }
    </style>
</head>
<body>
<div class="header">
    <div>
        <h1>INVOICE</h1>
        <p><strong>{{ $invoice->invoice_number }}</strong></p>
        <p>Date: {{ $invoice->created_at->format('d F Y') }}</p>
        @if($invoice->due_date)
        <p>Due: {{ $invoice->due_date->format('d F Y') }}</p>
        @endif
    </div>
    <div style="text-align:right">
        <h3 style="color:#6c63ff">IntuDash</h3>
        <p>SMS Campaign Services</p>
        <p><span class="badge">{{ ucfirst($invoice->status) }}</span></p>
    </div>
</div>

<div style="display:flex; justify-content:space-between; margin-bottom:20px;">
    <div>
        <strong>Bill To:</strong><br>
        {{ $invoice->client->company_name }}<br>
        {{ $invoice->client->contact_person }}<br>
        {{ $invoice->client->email }}<br>
        @if($invoice->client->billing_address){{ $invoice->client->billing_address }}<br>@endif
        @if($invoice->client->vat_number)VAT: {{ $invoice->client->vat_number }}@endif
    </div>
    <div>
        <strong>Campaign:</strong><br>
        {{ $invoice->campaign?->name ?? '—' }}
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Description</th>
            <th class="text-right">Quantity</th>
            <th class="text-right">Unit Price</th>
            <th class="text-right">Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach($invoice->items as $item)
        <tr>
            <td>{{ $item->description }}</td>
            <td class="text-right">{{ number_format($item->quantity) }}</td>
            <td class="text-right">R {{ number_format($item->unit_price, 4) }}</td>
            <td class="text-right">R {{ number_format($item->total, 2) }}</td>
        </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr><td colspan="3" class="text-right">Subtotal</td><td class="text-right">R {{ number_format($invoice->subtotal, 2) }}</td></tr>
        @if($invoice->vat_enabled)
        <tr><td colspan="3" class="text-right">VAT ({{ $invoice->vat_rate }}%)</td><td class="text-right">R {{ number_format($invoice->vat_amount, 2) }}</td></tr>
        @endif
        <tr class="totals"><td colspan="3" class="text-right" style="font-size:15px">TOTAL</td><td class="text-right" style="font-size:15px">R {{ number_format($invoice->total, 2) }}</td></tr>
    </tfoot>
</table>

<div class="footer">
    <p>Thank you for your business.@if($invoice->due_date) Payment is due by {{ $invoice->due_date->format('d F Y') }}.@endif</p>
    <p>Generated by IntuDash SMS Campaign Manager</p>
</div>
</body>
</html>
